/**
 * Music dataset for the workshop.
 * 40 widely-known songs high school students are likely to recognize, balanced across genres.
 * Each song has:
 * - id: unique identifier (s01-s40)
 * - title: song name
 * - artist: artist name
 * - genre: one of 10 genres (Pop, Rock, Hip-Hop, EDM, R&B, Jazz, Classical, Country, Indie, Ambient)
 * - tempo: BPM (approximate), normalized later by dividing by 200
 * - energy: 0-1 (how intense/active)
 * - danceability: 0-1 (how suitable for dancing)
 * - valence: 0-1 (musical positivity/happiness)
 */

const songs = [
  // Pop
  {
    id: "s01",
    title: "Levitating",
    artist: "Dua Lipa",
    genre: "Pop",
    tempo: 103,
    energy: 0.8,
    danceability: 0.9,
    valence: 0.9,
  },
  {
    id: "s02",
    title: "Blinding Lights",
    artist: "The Weeknd",
    genre: "Pop",
    tempo: 171,
    energy: 0.85,
    danceability: 0.8,
    valence: 0.7,
  },
  {
    id: "s03",
    title: "As It Was",
    artist: "Harry Styles",
    genre: "Pop",
    tempo: 86,
    energy: 0.6,
    danceability: 0.82,
    valence: 0.7,
  },
  {
    id: "s04",
    title: "Shake It Off",
    artist: "Taylor Swift",
    genre: "Pop",
    tempo: 160,
    energy: 0.85,
    danceability: 0.86,
    valence: 0.92,
  },

  // Rock
  {
    id: "s05",
    title: "Believer",
    artist: "Imagine Dragons",
    genre: "Rock",
    tempo: 125,
    energy: 0.92,
    danceability: 0.5,
    valence: 0.6,
  },
  {
    id: "s06",
    title: "Seven Nation Army",
    artist: "The White Stripes",
    genre: "Rock",
    tempo: 124,
    energy: 0.85,
    danceability: 0.52,
    valence: 0.6,
  },
  {
    id: "s07",
    title: "Smells Like Teen Spirit",
    artist: "Nirvana",
    genre: "Rock",
    tempo: 117,
    energy: 0.95,
    danceability: 0.4,
    valence: 0.5,
  },
  {
    id: "s08",
    title: "Mr. Brightside",
    artist: "The Killers",
    genre: "Rock",
    tempo: 148,
    energy: 0.9,
    danceability: 0.58,
    valence: 0.7,
  },

  // Hip-Hop
  {
    id: "s09",
    title: "SICKO MODE",
    artist: "Travis Scott",
    genre: "Hip-Hop",
    tempo: 78,
    energy: 0.82,
    danceability: 0.8,
    valence: 0.5,
  },
  {
    id: "s10",
    title: "HUMBLE.",
    artist: "Kendrick Lamar",
    genre: "Hip-Hop",
    tempo: 150,
    energy: 0.82,
    danceability: 0.72,
    valence: 0.5,
  },
  {
    id: "s11",
    title: "God's Plan",
    artist: "Drake",
    genre: "Hip-Hop",
    tempo: 77,
    energy: 0.7,
    danceability: 0.8,
    valence: 0.6,
  },
  {
    id: "s12",
    title: "Old Town Road",
    artist: "Lil Nas X",
    genre: "Hip-Hop",
    tempo: 136,
    energy: 0.62,
    danceability: 0.92,
    valence: 0.85,
  },

  // EDM
  {
    id: "s13",
    title: "Wake Me Up",
    artist: "Avicii",
    genre: "EDM",
    tempo: 124,
    energy: 0.9,
    danceability: 0.9,
    valence: 0.8,
  },
  {
    id: "s14",
    title: "Titanium",
    artist: "David Guetta ft. Sia",
    genre: "EDM",
    tempo: 126,
    energy: 0.92,
    danceability: 0.82,
    valence: 0.6,
  },
  {
    id: "s15",
    title: "Where Are Ü Now",
    artist: "Skrillex & Diplo",
    genre: "EDM",
    tempo: 140,
    energy: 0.85,
    danceability: 0.8,
    valence: 0.6,
  },
  {
    id: "s16",
    title: "Animals",
    artist: "Martin Garrix",
    genre: "EDM",
    tempo: 128,
    energy: 0.98,
    danceability: 0.92,
    valence: 0.7,
  },

  // R&B
  {
    id: "s17",
    title: "Peaches",
    artist: "Justin Bieber ft. Daniel Caesar",
    genre: "R&B",
    tempo: 90,
    energy: 0.6,
    danceability: 0.82,
    valence: 0.75,
  },
  {
    id: "s18",
    title: "Kiss Me More",
    artist: "Doja Cat ft. SZA",
    genre: "R&B",
    tempo: 111,
    energy: 0.7,
    danceability: 0.82,
    valence: 0.9,
  },
  {
    id: "s19",
    title: "Leave The Door Open",
    artist: "Silk Sonic",
    genre: "R&B",
    tempo: 74,
    energy: 0.5,
    danceability: 0.6,
    valence: 0.85,
  },
  {
    id: "s20",
    title: "Die For You",
    artist: "The Weeknd",
    genre: "R&B",
    tempo: 134,
    energy: 0.62,
    danceability: 0.7,
    valence: 0.6,
  },

  // Jazz
  {
    id: "s21",
    title: "Take Five",
    artist: "The Dave Brubeck Quartet",
    genre: "Jazz",
    tempo: 174,
    energy: 0.55,
    danceability: 0.5,
    valence: 0.6,
  },
  {
    id: "s22",
    title: "Sing, Sing, Sing",
    artist: "Benny Goodman",
    genre: "Jazz",
    tempo: 110,
    energy: 0.8,
    danceability: 0.72,
    valence: 0.7,
  },
  {
    id: "s23",
    title: "What a Wonderful World",
    artist: "Louis Armstrong",
    genre: "Jazz",
    tempo: 66,
    energy: 0.3,
    danceability: 0.3,
    valence: 0.85,
  },
  {
    id: "s24",
    title: "Fly Me to the Moon",
    artist: "Frank Sinatra",
    genre: "Jazz",
    tempo: 120,
    energy: 0.62,
    danceability: 0.62,
    valence: 0.9,
  },

  // Classical
  {
    id: "s25",
    title: "Für Elise",
    artist: "Ludwig van Beethoven",
    genre: "Classical",
    tempo: 120,
    energy: 0.3,
    danceability: 0.2,
    valence: 0.6,
  },
  {
    id: "s26",
    title: "Clair de Lune",
    artist: "Claude Debussy",
    genre: "Classical",
    tempo: 66,
    energy: 0.2,
    danceability: 0.15,
    valence: 0.5,
  },
  {
    id: "s27",
    title: "Canon in D",
    artist: "Johann Pachelbel",
    genre: "Classical",
    tempo: 96,
    energy: 0.35,
    danceability: 0.3,
    valence: 0.7,
  },
  {
    id: "s28",
    title: "Spring (The Four Seasons)",
    artist: "Antonio Vivaldi",
    genre: "Classical",
    tempo: 92,
    energy: 0.5,
    danceability: 0.25,
    valence: 0.8,
  },

  // Country
  {
    id: "s29",
    title: "Cruise",
    artist: "Florida Georgia Line",
    genre: "Country",
    tempo: 148,
    energy: 0.7,
    danceability: 0.7,
    valence: 0.92,
  },
  {
    id: "s30",
    title: "Body Like a Back Road",
    artist: "Sam Hunt",
    genre: "Country",
    tempo: 96,
    energy: 0.6,
    danceability: 0.7,
    valence: 0.85,
  },
  {
    id: "s31",
    title: "You Belong With Me",
    artist: "Taylor Swift",
    genre: "Country",
    tempo: 131,
    energy: 0.7,
    danceability: 0.7,
    valence: 0.92,
  },
  {
    id: "s32",
    title: "Tennessee Whiskey",
    artist: "Chris Stapleton",
    genre: "Country",
    tempo: 63,
    energy: 0.5,
    danceability: 0.5,
    valence: 0.6,
  },

  // Indie
  {
    id: "s33",
    title: "Riptide",
    artist: "Vance Joy",
    genre: "Indie",
    tempo: 100,
    energy: 0.6,
    danceability: 0.6,
    valence: 0.8,
  },
  {
    id: "s34",
    title: "Sweater Weather",
    artist: "The Neighbourhood",
    genre: "Indie",
    tempo: 115,
    energy: 0.6,
    danceability: 0.52,
    valence: 0.5,
  },
  {
    id: "s35",
    title: "Somebody Else",
    artist: "The 1975",
    genre: "Indie",
    tempo: 93,
    energy: 0.5,
    danceability: 0.5,
    valence: 0.4,
  },
  {
    id: "s36",
    title: "Ocean Eyes",
    artist: "Billie Eilish",
    genre: "Indie",
    tempo: 145,
    energy: 0.3,
    danceability: 0.52,
    valence: 0.5,
  },

  // Ambient / Chill
  {
    id: "s37",
    title: "Weightless",
    artist: "Marconi Union",
    genre: "Ambient",
    tempo: 65,
    energy: 0.2,
    danceability: 0.18,
    valence: 0.4,
  },
  {
    id: "s38",
    title: "Sunset Lover",
    artist: "Petit Biscuit",
    genre: "Ambient",
    tempo: 87,
    energy: 0.4,
    danceability: 0.55,
    valence: 0.6,
  },
  {
    id: "s39",
    title: "Breathe",
    artist: "Télépopmusik",
    genre: "Ambient",
    tempo: 123,
    energy: 0.4,
    danceability: 0.6,
    valence: 0.5,
  },
  {
    id: "s40",
    title: "Experience",
    artist: "Ludovico Einaudi",
    genre: "Ambient",
    tempo: 80,
    energy: 0.4,
    danceability: 0.2,
    valence: 0.5,
  },

  // Pop - more
  {
    id: "s41",
    title: "Uptown Funk",
    artist: "Mark Ronson ft. Bruno Mars",
    genre: "Pop",
    tempo: 115,
    energy: 0.9,
    danceability: 0.92,
    valence: 0.95,
  },
  {
    id: "s42",
    title: "bad guy",
    artist: "Billie Eilish",
    genre: "Pop",
    tempo: 135,
    energy: 0.7,
    danceability: 0.84,
    valence: 0.56,
  },
  {
    id: "s43",
    title: "Firework",
    artist: "Katy Perry",
    genre: "Pop",
    tempo: 124,
    energy: 0.88,
    danceability: 0.64,
    valence: 0.93,
  },
  {
    id: "s44",
    title: "Shape of You",
    artist: "Ed Sheeran",
    genre: "Pop",
    tempo: 96,
    energy: 0.75,
    danceability: 0.83,
    valence: 0.6,
  },
  {
    id: "s45",
    title: "Call Me Maybe",
    artist: "Carly Rae Jepsen",
    genre: "Pop",
    tempo: 120,
    energy: 0.75,
    danceability: 0.75,
    valence: 0.9,
  },
  {
    id: "s46",
    title: "Anti-Hero",
    artist: "Taylor Swift",
    genre: "Pop",
    tempo: 97,
    energy: 0.7,
    danceability: 0.7,
    valence: 0.5,
  },
  {
    id: "s47",
    title: "Happy",
    artist: "Pharrell Williams",
    genre: "Pop",
    tempo: 160,
    energy: 0.83,
    danceability: 0.79,
    valence: 0.98,
  },
  {
    id: "s48",
    title: "Shut Up and Dance",
    artist: "WALK THE MOON",
    genre: "Pop",
    tempo: 128,
    energy: 0.9,
    danceability: 0.74,
    valence: 0.95,
  },
  {
    id: "s49",
    title: "Counting Stars",
    artist: "OneRepublic",
    genre: "Pop",
    tempo: 122,
    energy: 0.82,
    danceability: 0.68,
    valence: 0.62,
  },
  {
    id: "s50",
    title: "Don't Start Now",
    artist: "Dua Lipa",
    genre: "Pop",
    tempo: 124,
    energy: 0.85,
    danceability: 0.79,
    valence: 0.65,
  },

  // Rock - more
  {
    id: "s51",
    title: "Sweet Child O' Mine",
    artist: "Guns N' Roses",
    genre: "Rock",
    tempo: 125,
    energy: 0.9,
    danceability: 0.47,
    valence: 0.6,
  },
  {
    id: "s52",
    title: "Hotel California",
    artist: "Eagles",
    genre: "Rock",
    tempo: 75,
    energy: 0.5,
    danceability: 0.38,
    valence: 0.55,
  },
  {
    id: "s53",
    title: "Bohemian Rhapsody",
    artist: "Queen",
    genre: "Rock",
    tempo: 144,
    energy: 0.7,
    danceability: 0.35,
    valence: 0.6,
  },
  {
    id: "s54",
    title: "Another One Bites the Dust",
    artist: "Queen",
    genre: "Rock",
    tempo: 110,
    energy: 0.8,
    danceability: 0.7,
    valence: 0.6,
  },
  {
    id: "s55",
    title: "Radioactive",
    artist: "Imagine Dragons",
    genre: "Rock",
    tempo: 136,
    energy: 0.85,
    danceability: 0.54,
    valence: 0.4,
  },
  {
    id: "s56",
    title: "Enter Sandman",
    artist: "Metallica",
    genre: "Rock",
    tempo: 123,
    energy: 0.95,
    danceability: 0.42,
    valence: 0.45,
  },
  {
    id: "s57",
    title: "Chop Suey!",
    artist: "System Of A Down",
    genre: "Rock",
    tempo: 127,
    energy: 0.98,
    danceability: 0.45,
    valence: 0.4,
  },
  {
    id: "s58",
    title: "American Idiot",
    artist: "Green Day",
    genre: "Rock",
    tempo: 186,
    energy: 0.96,
    danceability: 0.38,
    valence: 0.6,
  },
  {
    id: "s59",
    title: "All Star",
    artist: "Smash Mouth",
    genre: "Rock",
    tempo: 104,
    energy: 0.8,
    danceability: 0.72,
    valence: 0.9,
  },
  {
    id: "s60",
    title: "Don't Stop Believin'",
    artist: "Journey",
    genre: "Rock",
    tempo: 119,
    energy: 0.8,
    danceability: 0.5,
    valence: 0.9,
  },

  // Hip-Hop - more
  {
    id: "s61",
    title: "Lose Yourself",
    artist: "Eminem",
    genre: "Hip-Hop",
    tempo: 171,
    energy: 0.85,
    danceability: 0.6,
    valence: 0.4,
  },
  {
    id: "s62",
    title: "Stronger",
    artist: "Kanye West",
    genre: "Hip-Hop",
    tempo: 104,
    energy: 0.8,
    danceability: 0.72,
    valence: 0.5,
  },
  {
    id: "s63",
    title: "Sunflower",
    artist: "Post Malone & Swae Lee",
    genre: "Hip-Hop",
    tempo: 90,
    energy: 0.6,
    danceability: 0.76,
    valence: 0.6,
  },
  {
    id: "s64",
    title: "ROCKSTAR",
    artist: "DaBaby ft. Roddy Ricch",
    genre: "Hip-Hop",
    tempo: 91,
    energy: 0.7,
    danceability: 0.73,
    valence: 0.4,
  },
  {
    id: "s65",
    title: "Lucid Dreams",
    artist: "Juice WRLD",
    genre: "Hip-Hop",
    tempo: 84,
    energy: 0.55,
    danceability: 0.63,
    valence: 0.2,
  },
  {
    id: "s66",
    title: "Godzilla",
    artist: "Eminem ft. Juice WRLD",
    genre: "Hip-Hop",
    tempo: 166,
    energy: 0.9,
    danceability: 0.78,
    valence: 0.45,
  },
  {
    id: "s67",
    title: "Trap Queen",
    artist: "Fetty Wap",
    genre: "Hip-Hop",
    tempo: 148,
    energy: 0.82,
    danceability: 0.77,
    valence: 0.6,
  },
  {
    id: "s68",
    title: "In Da Club",
    artist: "50 Cent",
    genre: "Hip-Hop",
    tempo: 90,
    energy: 0.8,
    danceability: 0.85,
    valence: 0.6,
  },
  {
    id: "s69",
    title: "Lose Control",
    artist: "Missy Elliott",
    genre: "Hip-Hop",
    tempo: 125,
    energy: 0.9,
    danceability: 0.88,
    valence: 0.65,
  },
  {
    id: "s70",
    title: "XO TOUR Llif3",
    artist: "Lil Uzi Vert",
    genre: "Hip-Hop",
    tempo: 155,
    energy: 0.6,
    danceability: 0.7,
    valence: 0.3,
  },

  // EDM - more
  {
    id: "s71",
    title: "Levels",
    artist: "Avicii",
    genre: "EDM",
    tempo: 126,
    energy: 0.9,
    danceability: 0.86,
    valence: 0.8,
  },
  {
    id: "s72",
    title: "Don't You Worry Child",
    artist: "Swedish House Mafia",
    genre: "EDM",
    tempo: 129,
    energy: 0.9,
    danceability: 0.6,
    valence: 0.6,
  },
  {
    id: "s73",
    title: "Closer",
    artist: "The Chainsmokers",
    genre: "EDM",
    tempo: 95,
    energy: 0.7,
    danceability: 0.76,
    valence: 0.6,
  },
  {
    id: "s74",
    title: "Lean On",
    artist: "Major Lazer & DJ Snake",
    genre: "EDM",
    tempo: 98,
    energy: 0.8,
    danceability: 0.84,
    valence: 0.6,
  },
  {
    id: "s75",
    title: "Turn Down for What",
    artist: "DJ Snake & Lil Jon",
    genre: "EDM",
    tempo: 100,
    energy: 0.98,
    danceability: 0.7,
    valence: 0.6,
  },
  {
    id: "s76",
    title: "Strobe",
    artist: "deadmau5",
    genre: "EDM",
    tempo: 128,
    energy: 0.7,
    danceability: 0.65,
    valence: 0.4,
  },
  {
    id: "s77",
    title: "Silence",
    artist: "Marshmello ft. Khalid",
    genre: "EDM",
    tempo: 142,
    energy: 0.6,
    danceability: 0.66,
    valence: 0.4,
  },
  {
    id: "s78",
    title: "Faded",
    artist: "Alan Walker",
    genre: "EDM",
    tempo: 90,
    energy: 0.6,
    danceability: 0.6,
    valence: 0.3,
  },
  {
    id: "s79",
    title: "Scary Monsters and Nice Sprites",
    artist: "Skrillex",
    genre: "EDM",
    tempo: 140,
    energy: 0.98,
    danceability: 0.6,
    valence: 0.5,
  },
  {
    id: "s80",
    title: "Clarity",
    artist: "Zedd ft. Foxes",
    genre: "EDM",
    tempo: 128,
    energy: 0.9,
    danceability: 0.72,
    valence: 0.6,
  },

  // R&B - more
  {
    id: "s81",
    title: "No Guidance",
    artist: "Chris Brown ft. Drake",
    genre: "R&B",
    tempo: 93,
    energy: 0.6,
    danceability: 0.75,
    valence: 0.5,
  },
  {
    id: "s82",
    title: "Blame It",
    artist: "Jamie Foxx ft. T-Pain",
    genre: "R&B",
    tempo: 93,
    energy: 0.7,
    danceability: 0.75,
    valence: 0.6,
  },
  {
    id: "s83",
    title: "The Weekend",
    artist: "SZA",
    genre: "R&B",
    tempo: 79,
    energy: 0.55,
    danceability: 0.6,
    valence: 0.45,
  },
  {
    id: "s84",
    title: "Adorn",
    artist: "Miguel",
    genre: "R&B",
    tempo: 134,
    energy: 0.6,
    danceability: 0.7,
    valence: 0.7,
  },
  {
    id: "s85",
    title: "Earned It",
    artist: "The Weeknd",
    genre: "R&B",
    tempo: 84,
    energy: 0.4,
    danceability: 0.4,
    valence: 0.35,
  },
  {
    id: "s86",
    title: "Thinkin Bout You",
    artist: "Frank Ocean",
    genre: "R&B",
    tempo: 81,
    energy: 0.35,
    danceability: 0.5,
    valence: 0.4,
  },
  {
    id: "s87",
    title: "Location",
    artist: "Khalid",
    genre: "R&B",
    tempo: 90,
    energy: 0.45,
    danceability: 0.6,
    valence: 0.5,
  },
  {
    id: "s88",
    title: "We Belong Together",
    artist: "Mariah Carey",
    genre: "R&B",
    tempo: 71,
    energy: 0.55,
    danceability: 0.45,
    valence: 0.45,
  },
  {
    id: "s89",
    title: "Say My Name",
    artist: "Destiny's Child",
    genre: "R&B",
    tempo: 104,
    energy: 0.8,
    danceability: 0.78,
    valence: 0.75,
  },
  {
    id: "s90",
    title: "Crazy in Love",
    artist: "Beyoncé ft. Jay-Z",
    genre: "R&B",
    tempo: 99,
    energy: 0.9,
    danceability: 0.74,
    valence: 0.9,
  },

  // Jazz - more
  {
    id: "s91",
    title: "So What",
    artist: "Miles Davis",
    genre: "Jazz",
    tempo: 138,
    energy: 0.4,
    danceability: 0.35,
    valence: 0.5,
  },
  {
    id: "s92",
    title: "Take the 'A' Train",
    artist: "Duke Ellington",
    genre: "Jazz",
    tempo: 167,
    energy: 0.6,
    danceability: 0.55,
    valence: 0.7,
  },
  {
    id: "s93",
    title: "Autumn Leaves",
    artist: "Cannonball Adderley",
    genre: "Jazz",
    tempo: 140,
    energy: 0.4,
    danceability: 0.35,
    valence: 0.5,
  },
  {
    id: "s94",
    title: "Cantaloupe Island",
    artist: "Herbie Hancock",
    genre: "Jazz",
    tempo: 124,
    energy: 0.5,
    danceability: 0.55,
    valence: 0.6,
  },
  {
    id: "s95",
    title: "My Favorite Things",
    artist: "John Coltrane",
    genre: "Jazz",
    tempo: 142,
    energy: 0.5,
    danceability: 0.4,
    valence: 0.6,
  },
  {
    id: "s96",
    title: "The Girl from Ipanema",
    artist: "Stan Getz & João Gilberto",
    genre: "Jazz",
    tempo: 128,
    energy: 0.35,
    danceability: 0.55,
    valence: 0.7,
  },
  {
    id: "s97",
    title: "Blue in Green",
    artist: "Miles Davis",
    genre: "Jazz",
    tempo: 60,
    energy: 0.2,
    danceability: 0.2,
    valence: 0.4,
  },
  {
    id: "s98",
    title: "All of Me",
    artist: "Ella Fitzgerald",
    genre: "Jazz",
    tempo: 149,
    energy: 0.55,
    danceability: 0.6,
    valence: 0.8,
  },
  {
    id: "s99",
    title: "It Don't Mean a Thing",
    artist: "Duke Ellington",
    genre: "Jazz",
    tempo: 140,
    energy: 0.7,
    danceability: 0.7,
    valence: 0.8,
  },
  {
    id: "s100",
    title: "Moanin'",
    artist: "Art Blakey & The Jazz Messengers",
    genre: "Jazz",
    tempo: 145,
    energy: 0.6,
    danceability: 0.5,
    valence: 0.6,
  },

  // Classical - more
  {
    id: "s101",
    title: "Moonlight Sonata (1st Movement)",
    artist: "Ludwig van Beethoven",
    genre: "Classical",
    tempo: 69,
    energy: 0.2,
    danceability: 0.1,
    valence: 0.3,
  },
  {
    id: "s102",
    title: "Eine kleine Nachtmusik",
    artist: "Wolfgang Amadeus Mozart",
    genre: "Classical",
    tempo: 120,
    energy: 0.5,
    danceability: 0.2,
    valence: 0.7,
  },
  {
    id: "s103",
    title: "Air on the G String",
    artist: "Johann Sebastian Bach",
    genre: "Classical",
    tempo: 50,
    energy: 0.2,
    danceability: 0.1,
    valence: 0.5,
  },
  {
    id: "s104",
    title: "Swan Lake (Theme)",
    artist: "Pyotr Ilyich Tchaikovsky",
    genre: "Classical",
    tempo: 138,
    energy: 0.5,
    danceability: 0.15,
    valence: 0.5,
  },
  {
    id: "s105",
    title: "Nocturne Op. 9 No. 2",
    artist: "Frédéric Chopin",
    genre: "Classical",
    tempo: 85,
    energy: 0.25,
    danceability: 0.12,
    valence: 0.5,
  },
  {
    id: "s106",
    title: "In the Hall of the Mountain King",
    artist: "Edvard Grieg",
    genre: "Classical",
    tempo: 132,
    energy: 0.7,
    danceability: 0.2,
    valence: 0.6,
  },
  {
    id: "s107",
    title: "Boléro",
    artist: "Maurice Ravel",
    genre: "Classical",
    tempo: 72,
    energy: 0.45,
    danceability: 0.2,
    valence: 0.6,
  },
  {
    id: "s108",
    title: "Ride of the Valkyries",
    artist: "Richard Wagner",
    genre: "Classical",
    tempo: 112,
    energy: 0.9,
    danceability: 0.1,
    valence: 0.6,
  },
  {
    id: "s109",
    title: "The Blue Danube",
    artist: "Johann Strauss II",
    genre: "Classical",
    tempo: 156,
    energy: 0.5,
    danceability: 0.25,
    valence: 0.7,
  },
  {
    id: "s110",
    title: "Gymnopédie No.1",
    artist: "Erik Satie",
    genre: "Classical",
    tempo: 80,
    energy: 0.15,
    danceability: 0.1,
    valence: 0.4,
  },

  // Country - more
  {
    id: "s111",
    title: "Before He Cheats",
    artist: "Carrie Underwood",
    genre: "Country",
    tempo: 130,
    energy: 0.8,
    danceability: 0.6,
    valence: 0.6,
  },
  {
    id: "s112",
    title: "Need You Now",
    artist: "Lady A",
    genre: "Country",
    tempo: 108,
    energy: 0.5,
    danceability: 0.5,
    valence: 0.5,
  },
  {
    id: "s113",
    title: "Wagon Wheel",
    artist: "Darius Rucker",
    genre: "Country",
    tempo: 75,
    energy: 0.6,
    danceability: 0.55,
    valence: 0.8,
  },
  {
    id: "s114",
    title: "Take Me Home, Country Roads",
    artist: "John Denver",
    genre: "Country",
    tempo: 82,
    energy: 0.6,
    danceability: 0.5,
    valence: 0.9,
  },
  {
    id: "s115",
    title: "Friends in Low Places",
    artist: "Garth Brooks",
    genre: "Country",
    tempo: 92,
    energy: 0.6,
    danceability: 0.58,
    valence: 0.8,
  },
  {
    id: "s116",
    title: "Life Is a Highway",
    artist: "Rascal Flatts",
    genre: "Country",
    tempo: 104,
    energy: 0.85,
    danceability: 0.66,
    valence: 0.9,
  },
  {
    id: "s117",
    title: "Tequila",
    artist: "Dan + Shay",
    genre: "Country",
    tempo: 86,
    energy: 0.5,
    danceability: 0.55,
    valence: 0.4,
  },
  {
    id: "s118",
    title: "Die a Happy Man",
    artist: "Thomas Rhett",
    genre: "Country",
    tempo: 74,
    energy: 0.5,
    danceability: 0.55,
    valence: 0.55,
  },
  {
    id: "s119",
    title: "Speechless",
    artist: "Dan + Shay",
    genre: "Country",
    tempo: 75,
    energy: 0.4,
    danceability: 0.45,
    valence: 0.5,
  },
  {
    id: "s120",
    title: "Buy Me a Boat",
    artist: "Chris Janson",
    genre: "Country",
    tempo: 112,
    energy: 0.7,
    danceability: 0.64,
    valence: 0.7,
  },

  // Indie - more
  {
    id: "s121",
    title: "Dog Days Are Over",
    artist: "Florence + The Machine",
    genre: "Indie",
    tempo: 150,
    energy: 0.8,
    danceability: 0.6,
    valence: 0.7,
  },
  {
    id: "s122",
    title: "Electric Feel",
    artist: "MGMT",
    genre: "Indie",
    tempo: 98,
    energy: 0.7,
    danceability: 0.78,
    valence: 0.7,
  },
  {
    id: "s123",
    title: "Pumped Up Kicks",
    artist: "Foster the People",
    genre: "Indie",
    tempo: 128,
    energy: 0.6,
    danceability: 0.7,
    valence: 0.6,
  },
  {
    id: "s124",
    title: "Mr. Blue Sky",
    artist: "Electric Light Orchestra",
    genre: "Indie",
    tempo: 178,
    energy: 0.9,
    danceability: 0.6,
    valence: 0.95,
  },
  {
    id: "s125",
    title: "Holocene",
    artist: "Bon Iver",
    genre: "Indie",
    tempo: 72,
    energy: 0.3,
    danceability: 0.35,
    valence: 0.4,
  },
  {
    id: "s126",
    title: "Take Me Out",
    artist: "Franz Ferdinand",
    genre: "Indie",
    tempo: 104,
    energy: 0.86,
    danceability: 0.6,
    valence: 0.65,
  },
  {
    id: "s127",
    title: "Little Talks",
    artist: "Of Monsters and Men",
    genre: "Indie",
    tempo: 105,
    energy: 0.8,
    danceability: 0.6,
    valence: 0.8,
  },
  {
    id: "s128",
    title: "Yellow",
    artist: "Coldplay",
    genre: "Indie",
    tempo: 86,
    energy: 0.5,
    danceability: 0.45,
    valence: 0.5,
  },
  {
    id: "s129",
    title: "First Day of My Life",
    artist: "Bright Eyes",
    genre: "Indie",
    tempo: 97,
    energy: 0.3,
    danceability: 0.5,
    valence: 0.6,
  },
  {
    id: "s130",
    title: "Reptilia",
    artist: "The Strokes",
    genre: "Indie",
    tempo: 160,
    energy: 0.9,
    danceability: 0.5,
    valence: 0.6,
  },

  // Ambient - more
  {
    id: "s131",
    title: "Spiegel im Spiegel",
    artist: "Arvo Pärt",
    genre: "Ambient",
    tempo: 78,
    energy: 0.15,
    danceability: 0.1,
    valence: 0.4,
  },
  {
    id: "s132",
    title: "An Ending (Ascent)",
    artist: "Brian Eno",
    genre: "Ambient",
    tempo: 77,
    energy: 0.1,
    danceability: 0.1,
    valence: 0.4,
  },
  {
    id: "s133",
    title: "We Played Some Open Chords",
    artist: "Hammock",
    genre: "Ambient",
    tempo: 60,
    energy: 0.2,
    danceability: 0.1,
    valence: 0.4,
  },
  {
    id: "s134",
    title: "Borealis",
    artist: "Ólafur Arnalds",
    genre: "Ambient",
    tempo: 70,
    energy: 0.2,
    danceability: 0.18,
    valence: 0.45,
  },
  {
    id: "s135",
    title: "Midnight City",
    artist: "M83",
    genre: "Ambient",
    tempo: 105,
    energy: 0.65,
    danceability: 0.6,
    valence: 0.6,
  },
  {
    id: "s136",
    title: "Outro",
    artist: "M83",
    genre: "Ambient",
    tempo: 76,
    energy: 0.5,
    danceability: 0.2,
    valence: 0.5,
  },
  {
    id: "s137",
    title: "Dayvan Cowboy",
    artist: "Boards of Canada",
    genre: "Ambient",
    tempo: 82,
    energy: 0.4,
    danceability: 0.4,
    valence: 0.5,
  },
  {
    id: "s138",
    title: "Song for Zula",
    artist: "Phosphorescent",
    genre: "Ambient",
    tempo: 112,
    energy: 0.5,
    danceability: 0.4,
    valence: 0.5,
  },
  {
    id: "s139",
    title: "Replica",
    artist: "Oneohtrix Point Never",
    genre: "Ambient",
    tempo: 80,
    energy: 0.3,
    danceability: 0.3,
    valence: 0.4,
  },
  {
    id: "s140",
    title: "Weightless, Pt. 2",
    artist: "Marconi Union",
    genre: "Ambient",
    tempo: 65,
    energy: 0.2,
    danceability: 0.15,
    valence: 0.4,
  },
];
